### ISSUE TITLE
How do you clear the input form in the fileDidChange function?

### ISSUE THREAD

**Issue by shicholas** [benefitcloud/ember-uploader#134]
It doesn't seem like there is a files property in the component that I could do something like:

```js
this.set('files', []);
```

Happy to write some docs on this issue if I know how to do this.

Thank you for this amazing library!

**Comment by digitaltoad** [comment]
The easiest way to do this is to recreate the input. I've done this in the past by removing the input when a file is selected as well as showing a clear button.

```handlebars
{{#if files}}
  <button {{action "clear"}}>Clear</button>
{{else}}
  {{file-field files=files}}
{{/if}}
```

You could also convert the `FileList` to an array and list the filenames/type or preview at this point. Let me know if this solves your issue.

**Comment by hectorh30** [comment]
@digitaltoad it did it for me, thanks a lot. I ended up creating a wrapper component to achieve this (besides the one that inherits `FileField`).

**Comment by dbinetti** [comment]
So I'm a total Ember newbie, but in your example @digitaltoad what exactly happens in your `action "clear"`?  I mean, if you're not calling `this.set('files', []);` then what are you doing?

My use case seems pretty common:  I'm uploading a file, then transitioning to a new record, and the file input field remains populated.  I'm also renaming the input to a canonical form, which is confusing users since the file name they uploaded is still there.  So basically I'm looking to clear it after every successful upload... thanks

**Comment by digitaltoad** [comment]
In that example I would be doing that but `files` in this case isn't on the field itself but the controller. When a file is selected, I populate `files` on the controller which in turn removes the file field from the view. The best way to clear a file field of its value is to recreate it. The clear action would indeed execute `this.set('files', [])` which in turn would create a new file field.
