### ISSUE TITLE
Update README to reflect ES6 module changes

### ISSUE THREAD

**Issue by digitaltoad** [benefitcloud/ember-uploader#34]

**Comment by eaglevision20** [comment]
I've been trying to get this integrated into a new cli project I'm working on. It looks like the perfect solution to my need for file uploads to s3. But, I'm having some issues getting it kicked off with the cli project. I believe it is simply because I'm not referencing the addon properly. My current implementation has looked like this:

npm install --save-dev ember-cli-uploader
ember generate ember-cli-uploader
ember g component file-upload --pod

```javascript
//components/file-upload/component.js

import Ember from 'ember';

export default Ember.FileField.extend({
  url: '',
  filesDidChange: (function() {
    var uploadUrl = this.get('url');
    var files = this.get('files');

    var uploader = Ember.Uploader.create({
      url: uploadUrl
    });

    if (!Ember.isEmpty(files)) {
      uploader.upload(files[0]);
    }
  }).observes('files')
});

```
I then implement {{file-uploader url="/upload"}} on my dashboard template but receive the following error:
Uncaught TypeError: Cannot read property 'extend' of undefined

This error is being generated from Ember.FileField.extend ... 

How do I need to reference this properly?

Any help would be greatly appreciated.

**Comment by digitaltoad** [comment]
Sorry, the namespace has changed. You need to import the uploader like you have ember.import Uploader from 'ember-uploader/uploader';-JoshOn Wed, Jan 21, 2015 at 11:34 AM,  benefitcloud/ember-uploader <reply@reply.github.com> wrote:            I've been trying to get this integrated into a new cli project I'm working on. It looks like the perfect solution to my need for file uploads to s3. But, I'm having some issues getting it kicked off with the cli project. I believe it is simply because I'm not referencing the addon properly. My current implementation has looked like this:

npm install --save-dev ember-cli-uploader
ember generate ember-cli-uploader
ember g component file-upload --pod

//components/file-upload/component.js

import Ember from 'ember';

export default Ember.FileField.extend({
  url: '',
  filesDidChange: (function() {
    var uploadUrl = this.get('url');
    var files = this.get('files');

    var uploader = Ember.Uploader.create({
      url: uploadUrl
    });

    if (!Ember.isEmpty(files)) {
      uploader.upload(files[0]);
    }
  }).observes('files')
});


I then implement {{file-uploader url="/upload"}} on my dashboard template but receive the following error:
Uncaught TypeError: Cannot read property 'extend' of undefined

This error is being generated from Ember.FileField.extend ... 

How do I need to reference this properly?

Any help would be greatly appreciated.

**Comment by eaglevision20** [comment]
Thanks for the speedy reply. I have included my working component code below.

```js 
import Ember from 'ember';
import EmberLoader from 'ember-uploader/uploader';
import FileField from 'ember-uploader/file-field';

export default FileField.extend({
  url: '',
  filesDidChange: (function() {
    var uploadUrl = this.get('url');
    var files = this.get('files');

    var uploader = EmberLoader.create({
      url: uploadUrl
    });

    if (!Ember.isEmpty(files)) {
      uploader.upload(files[0]);
    }
  }).observes('files')
});
```
 Thanks for building and sharing this great tool. I'm looking forward to playing more with it in the future!

**Comment by digitaltoad** [comment]
This should be done in the current master.
