### ISSUE TITLE
Back End Help

### ISSUE THREAD

**Issue by gte451f** [benefitcloud/ember-uploader#46]
This may be a dumb series of questions but I'm at a loss on what this component is expecting.

1) Does the component issues a single XHR request with the file data encoded in the post?

I ask because when I setup this component in my CLI based app, the component will issue and XHR but doesn't seem to send the actual file in the initial post.

See the attached screen shot of Request Headers and Payload issued to the server.
![uploaddata](https://cloud.githubusercontent.com/assets/2897569/5950451/58197fa4-a728-11e4-94e4-d56c2316d3a8.png)

2) My server side logic receives a request and is able to parse out the "meta data" around the file, but not the actual file contents.

So I'm left wondering, why does it look like my request lacks the actual file and the server not able to receive the file?

Maybe this component only works with Amazon S3?

**Comment by digitaltoad** [comment]
No it most definitely works without s3. Mind posting your uploader code?-JoshOn Wed, Jan 28, 2015 at 8:01 PM,  benefitcloud/ember-uploader <reply@reply.github.com> wrote:            This may be a dumb series of questions but I'm at a loss on what this component is expecting.

1) Does the component issues a single XHR request with the file data encoded in the post?

I ask because when I setup this component in my CLI based app, the component will issue and XHR but doesn't seem to send the actual file in the initial post.

See the attached screen shot of Request Headers and Payload issued to the server.


2) My server side logic receives a request and is able to parse out the "meta data" around the file, but not the actual file contents.

So I'm left wondering, why does it look like my request lacks the actual file and the server not able to receive the file?

Maybe this component only works with Amazon S3?

**Comment by gte451f** [comment]
False alarm!  After trying the same thing in Firefox, the FireBug console reveals binary data included in the post.  That pointed me back to a server side issue which appears to be something specific to my stack.
